[package]
name = "tumburu_daw"
description = "Tumburu Digital Audio Workstation"
version = "0.0.4"
edition = "2024"

[lib]
name = "tumburu"
path = "src/lib.rs"

[dependencies]
cpal = "0.18.2"
rodio = {
    version = "0.22.1",
    default-features = false,
    features = ["symphonia-all"]
}

[profile.dev]
lto = true
debug-assertions = true
overflow-checks = true
opt-level = 1
debug = "line-tables-only"
[profile.release]
lto = true
panic = "abort"
debug-assertions = false
overflow-checks = false
opt-level = 3
