name: Doc

on:
  push:
    branches: ["master"]
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone source
        uses: actions/checkout@v4
      - name: Install system dev build deps
        uses: ConorMacBride/install-package@v1.1.0
        with: 
          apt: dbus-devel alsa-lib-devel
      - name: Run doc build with all rustdoc features
        run: cargo doc
      - name: Create redirect index.html
        run: echo '<meta http-equiv="refresh" content="0; url=tumburu/index.html">' > target/doc/index.html
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: target/doc
  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5

