name: Rel
on:
  push:
    branches: ["master"]
    tags: ["v*"]
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write

env:
  CARGO_TERM_COLOR: always

jobs:
  build-release:
    runs-on: ubuntu-latest
    name: Build Release
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
      - name: Install ALSA dependencies (Linux)
        run: sudo apt-get update && sudo apt-get install -y libasound2-dev
      - name: Build Release Binary
        run: cargo build --release
